# Generated by Django 3.2.6 on 2021-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(to='users.Stock'),
        ),
    ]
