# Generated by Django 3.2.6 on 2021-08-18 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
