# Generated by Django 3.2.6 on 2021-08-18 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
