# Generated by Django 3.2.6 on 2021-08-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=200)),
                ('stock_name', models.CharField(max_length=200)),
                ('total', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='stocks',
            field=models.ManyToManyField(related_name='_app_user_stocks_+', to='app.UserStocks'),
        ),
    ]
