# Generated by Django 3.2.6 on 2021-08-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210821_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStocks',
            new_name='UserStock',
        ),
    ]
