# Generated by Django 3.2.6 on 2021-08-21 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_userstocks_userstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_on_hold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
