# Generated by Django 3.2.6 on 2021-08-21 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_money_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='stocks_on_hold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
