# Generated by Django 3.2.6 on 2021-08-21 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userstock_stocks_on_hold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=200)),
                ('upper_bound', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lower_bound', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
