# Generated by Django 3.2.6 on 2021-08-21 21:28

import app.models.order
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[(app.models.order.OrderType['SELL'], 'SELL'), (app.models.order.OrderType['BUY'], 'buy')], default='SELL', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='lower_bound',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
