# Generated by Django 3.2.6 on 2021-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy')], default='SELL', max_length=200),
        ),
    ]
