# Generated by Django 3.2.6 on 2021-08-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
