# Generated by Django 3.2.6 on 2021-08-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='choice_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='votes',
        ),
        migrations.AddField(
            model_name='stock',
            name='availability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
