# Generated by Django 3.2.6 on 2021-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210805_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='zoz', max_length=200),
            preserve_default=False,
        ),
    ]
