# Generated by Django 3.2.6 on 2021-08-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_userstocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stocks',
        ),
    ]
