# Generated by Django 3.2.6 on 2021-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_user_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstocks',
            name='stock',
        ),
        migrations.AddField(
            model_name='userstocks',
            name='stock_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
