# Generated by Django 3.2.6 on 2021-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210807_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstocks',
            name='stock_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
