# Generated by Django 3.2.6 on 2021-08-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_userstocks_stock_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
